name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black

    - name: Run Linter (flake8)
      run: |
        flake8 src/ tests/

    - name: Check formatting (black)
      run: |
        black --check src/ tests/

    - name: Run tests
      run: |
        PYTHONPATH=. pytest

    - name: Simulated Deploy
      if: success()
      run: |
        echo " Deploy automático simulado: código validado y listo para producción"



